Repository wecode-bootcamp-korea/35-1st-9roomdroom9-frontend, pull requests merged in 2022-07, with the labels that each got.

#1 Add: Fontawesome 패키치 설치
  package-lock.json
  package.json
Labels: 멘토 리뷰 요청

#2 [35기 엄성훈] Modify: LoginPage 리뷰 반영, 유효성 검사 추가
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
  src/pages/Login/LoginForm.js
  src/pages/Login/LoginForm.scss
Labels: 멘토 리뷰 요청, 수정 요청

#4 [35기 김광희] Modify: Footer component 리뷰 반영
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
Labels: 멘토 리뷰 요청

#3 [35기 김광희] Modify: Nav component 리뷰 반영
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
Labels: 멘토 리뷰 요청

#8 [35기 엄성훈] Add: 공통 Hook useParams Path Variable 경로 갱신
  src/Router.js
Labels: 멘토 리뷰 요청

#9 [35기 엄성훈] Refactor: JoinPage 정규식표현 추가, BE 통신 완료
  src/pages/Join/JoinForm.js
  src/pages/Join/JoinForm.scss
Labels: 멘토 리뷰 요청

#10 [35기 엄성훈] Refactor: LoginPage 불필요한 useState 소거, BE 통신 완료
  src/pages/Login/Login.js
  src/pages/Login/LoginForm.js
Labels: 멘토 리뷰 요청

#12 [35기 엄성훈] Add: 공통 Hook useParams Path Variable 경로 추가
  src/Router.js
Labels: 멘토 리뷰 요청

#6 [35기 정예빈] Modify: Main Page Components 분리 및 통신 테스트 완료
  public/data/itemListData.json
  public/data/main.json
  public/data/slide.json
  public/images/mainPage/arrow.png
  public/images/mainPage/banner-bg01.png
  public/images/mainPage/banner-bg02.png
  public/images/mainPage/main_arr_next.png
  public/images/mainPage/main_arr_next_on.png
  public/images/mainPage/main_arr_prev.png
  public/images/mainPage/main_arr_prev_on.png
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
  src/pages/Main/components/ProductsList.js
  src/pages/Main/components/ProductsList.scss
  src/pages/Slides/ImgList.js
  src/pages/Slides/ImgList.scss
  src/pages/Slides/MainSlide.js
  src/pages/Slides/MainSlide.scss
  src/pages/Slides/Slides.js
  src/pages/Slides/Slides.scss
Labels: 멘토 리뷰 요청

#11 [35기 김광희] 장바구니 페이지 레이아웃 및 기능구현
  public/data/cartList.json
  src/pages/Cart/Cart.js
  src/pages/Cart/Cart.scss
  src/pages/Cart/CartItem.js
Labels: 멘토 리뷰 요청

#14 [35기 엄성훈] Add: 공통 ScrollToTop 컴포넌트 추가
  src/Router.js
  src/components/Scroll/Scroll.js
Labels: 멘토 리뷰 요청

#7 [35기 엄성훈] Add: Product Detail Page, Tab Menu 기능구현, 리뷰반영
  public/data/itemDetailData.json
  public/images/itemDetail/itemDetail.jpeg
  public/images/itemDetail/itemslide.gif
  src/pages/ItemDetail/ItemDetail.js
  src/pages/ItemDetail/ItemDetail.scss
  src/pages/ItemDetail/components/First.js
  src/pages/ItemDetail/components/First.scss
  src/pages/ItemDetail/components/Second.js
  src/pages/ItemDetail/components/Second.scss
  src/pages/ItemDetail/components/Third.js
  src/pages/ItemDetail/components/Third.scss
Labels: 완료

#15 [35기 엄성훈] Add: Product List Page 레이아웃, 기능구현 추가
  src/pages/ItemList/ItemList.js
  src/pages/ItemList/ItemList.scss
Labels: 멘토 리뷰 요청

#16 [35기 엄성훈] Fix: fetch() 고정 IP값 추가
  public/data/slide.json
  public/images/ex.jpg
  public/images/itemDetail/itemDetail.jpeg
  public/images/itemDetail/itemDetail01.png
  public/images/itemDetail/itemDetail02.png
  public/images/itemDetail/itemslide.gif
  src/config.js
  src/pages/Cart/Cart.js
  src/pages/ItemDetail/ItemDetail.js
  src/pages/ItemList/ItemList.js
  src/pages/Join/JoinForm.js
  src/pages/Login/LoginForm.js
  src/pages/Main/Main.js
  src/pages/Slides/MainSlide.js
  src/pages/Slides/Slides.js
Labels: 멘토 리뷰 요청
